src/objects/External_File_Relationship__c.object
<CustomObject>
    <fields>
        <fullName>Object_ID__c</fullName>
        <label>Object ID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <label>External File Relationship</label>
    <nameField>
        <label>External File Relationship Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>External File Relationships</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/File_Upload_Setting__mdt.object
<CustomObject>
    <label>File Upload Setting</label>
    <pluralLabel>File Upload Settings</pluralLabel>
</CustomObject>

src/classes/Test_Service_Salesforce.cls
@isTest
public class Test_Service_Salesforce {

    @isTest
    public static void testSalesforceService(){
        Service_Salesforce salesforce = new Service_Salesforce(new File_Upload_Setting__mdt());
        Account account = new Account();
        account.name = 'test';
        insert account;
        
        File file = new File();
        file.file = 'Test';
        file.FileName = 'test';
        file.folder = 'test';
        list<String> objectIds =  new list<String>();
        objectIds.add(account.id);
        file.objectIds =objectIds;
            
            
        salesforce.UploadFile(file);
        
        list<External_File_Relationship__c> eFR = [select id from External_File_Relationship__c where Object_ID__c = :account.id];
        System.assertEquals(eFR.size(),1);
    }
    
}