src/objects/External_File__c.object
<CustomObject>
    <fields>
        <fullName>External_ID__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>External ID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Filename__c</fullName>
        <description>The name of the file.</description>
        <label>Filename</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Is_Private__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Private</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Mime_Type__c</fullName>
        <description>The MIME type of the file in question.</description>
        <label>Mime Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Public_URL__c</fullName>
        <label>Public URL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Tags__c</fullName>
        <globalPicklist>Filelink_Tags</globalPicklist>
        <label>Tags</label>
        <type>MultiselectPicklist</type>
    </fields>
    <label>External File</label>
    <nameField>
        <label>File Link Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>External Files</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/External_File_Relationship__c.object
<CustomObject>
    <fields>
        <fullName>Deleted__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Whether a record has been soft deleted.</description>
        <label>Deleted</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>External_File__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>External File</label>
        <referenceTo>External_File__c</referenceTo>
        <relationshipLabel>External File Relationships</relationshipLabel>
        <relationshipName>External_File_Relationships</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Object_ID__c</fullName>
        <label>Object ID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Tags__c</fullName>
        <globalPicklist>Filelink_Tags</globalPicklist>
        <label>Tags</label>
        <type>MultiselectPicklist</type>
    </fields>
    <label>External File Relationship</label>
    <nameField>
        <label>External File Relationship Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>External File Relationships</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/External_File_Relationship.cls
public class External_File_Relationship 
{    
    public static list<External_File_Relationship__c> getExternalFileRelationship(id sobjectId)
    {
        return [select id,External_File__r.Is_Private__c, External_File__r.Filename__c, External_File__r.Mime_Type__c, Tags__c,External_File__c, CreatedBy.Name, CreatedDate, External_File__r.External_ID__c ,External_File__r.Public_URL__c from External_File_Relationship__c where Object_ID__c = :sobjectId and Object_ID__c != null and Deleted__c=false order by CreatedDate Desc];
    }
    
    /**
    * @description Method to mark external file relationship records as deleted 
    * @param Set<Id> recordIdSet
    * @return 
    * @example
    */
    public static void removeFileRelationship(Set<Id> recordIdSet)
    {
        //Fetch records
        List<FileLInk__External_File_Relationship__c> lstFileRel = [SELECT Id,FileLInk__Deleted__c FROM FileLInk__External_File_Relationship__c WHERE Id IN:recordIdSet];
        
        for(FileLInk__External_File_Relationship__c objFileRel : lstFileRel)
        {
            //set deleted flag
            objFileRel.FileLInk__Deleted__c = true;
        }
        
        Database.update(lstFileRel);
    }
}