src/objects/External_File__c.object
<CustomObject>
    <fields>
        <fullName>External_ID__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>External ID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Filename__c</fullName>
        <description>The name of the file.</description>
        <label>Filename</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Public_URL__c</fullName>
        <label>Public URL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Service__c</fullName>
        <label>Service</label>
        <picklist>
            <picklistValues>
                <fullName>Cloudinary</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Tags__c</fullName>
        <globalPicklist>Filelink_Tags</globalPicklist>
        <label>Tags</label>
        <type>MultiselectPicklist</type>
    </fields>
    <label>External File</label>
    <nameField>
        <label>File Link Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>External Files</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/External_File_Relationship__c.object
<CustomObject>
    <fields>
        <fullName>External_File__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>External File</label>
        <referenceTo>External_File__c</referenceTo>
        <relationshipLabel>External File Relationships</relationshipLabel>
        <relationshipName>External_File_Relationships</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Object_ID__c</fullName>
        <label>Object ID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Tags__c</fullName>
        <globalPicklist>Filelink_Tags</globalPicklist>
        <label>Tags</label>
        <type>MultiselectPicklist</type>
    </fields>
    <label>External File Relationship</label>
    <nameField>
        <label>External File Relationship Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>External File Relationships</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/Service.cls
/*
 * Block comments with details of changes
 */
global virtual class Service
{
    global String ServiceName;
    public Service()
    {

    }

    public virtual void createExternalFileRelationship(String URL, String ObjectId){
    }

    global virtual External_File__c UploadFile(File file){
        System.debug('FileName '+file.FileName);
        file = upload(file);
        return  fileUploaded(file.externalID, file.fileURL, file);
    }
    
    global virtual file upload(File file){
        return null;
    }

    global virtual List<External_File_Relationship__c> relateFile(External_File__c ef, List<String> objectIds, List<String> tags) {
    
        List<External_File_Relationship__c> efrs = new list<External_File_Relationship__c>();
        
        for(String objectId: objectIds){
            External_File_Relationship__c efr = new External_File_Relationship__c();
            efr.Object_ID__c = objectId;
            efr.External_File__c = ef.id;
            efr.Tags__c = tags != null ? String.join(tags, ';') : null;
            efrs.add(efr);
        }
        insert efrs;
        
        return efrs;
    }

    global virtual List<External_File_Relationship__c> relateFile(External_File__c ef, List<String> objectIds) {
        return relateFile(ef, objectIds, null);
    }
 
    global virtual External_File__c findFileByExternalId(String externalId) {
        List<External_File__c> files = [
            SELECT 
                Id, External_Id__c, Tags__c, (SELECT Id, Object_Id__c, Tags__c FROM FileLink__External_File_Relationships__r)
            FROM
                External_File__c
            WHERE
                External_Id__c = :externalId
        ];
        
        return files.size() > 0 ? files[0] : null;  
    }
 
    public virtual External_File__c fileUploaded(String externalID, String url, File f){
        //List<External_File__c> lstextfile;
         //lstextfile = [SELECT id from External_File__c limit 1];

        List<String> objectIds = f.objectIds;
        List<String> tags = f.tags;
    
        External_File__c ef = new External_File__c();
        ef.FileLInk__External_ID__c = externalId;
        ef.Public_URL__c = url;
        ef.Service__c = ServiceName;
        ef.Filename__c = f.fileName;
        ef.FileLInk__Mime_Type__c = f.mimeType;
        
        for(String tag : tags){
            if(ef.tags__C == null){
                ef.tags__C = tag;
            }else{
                ef.tags__C = ef.tags__C +';'+tag;
            }
        }
      //added below lines for testing purpose
         //f.localCommit = true; 
        
         //lstextfile = [SELECT id from External_File__c limit 1];
        //end here
        if(f.localCommit){
            insert ef;            
            relateFile(ef, f.objectIds);
        }
        //lstextfile = [SELECT id from External_File__c limit 1]; //added this line for testing purpose
        return ef;
    }

    public class UploadException extends Exception {}
}