src/objects/External_File__c.object
<CustomObject>
    <fields>
        <fullName>Service__c</fullName>
        <label>Service</label>
        <picklist>
            <picklistValues>
                <fullName>Cloudinary</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Tags__c</fullName>
        <globalPicklist>Filelink_Tags</globalPicklist>
        <label>Tags</label>
        <type>MultiselectPicklist</type>
    </fields>
    <label>External File</label>
    <nameField>
        <label>File Link Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>External Files</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/External_File_Relationship__c.object
<CustomObject>
    <fields>
        <fullName>External_File__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>External File</label>
        <referenceTo>External_File__c</referenceTo>
        <relationshipLabel>External File Relationships</relationshipLabel>
        <relationshipName>External_File_Relationships</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Object_ID__c</fullName>
        <label>Object ID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Tags__c</fullName>
        <globalPicklist>Filelink_Tags</globalPicklist>
        <label>Tags</label>
        <type>MultiselectPicklist</type>
    </fields>
    <label>External File Relationship</label>
    <nameField>
        <label>External File Relationship Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>External File Relationships</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/File_Upload_Setting__mdt.object
<CustomObject>
    <fields>
        <fullName>API_Key__c</fullName>
        <label>API Key</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Config_JSON__c</fullName>
        <label>Config JSON</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Is_Default__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Is Default</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Private_Key__c</fullName>
        <label>Private Key</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Service__c</fullName>
        <label>Service</label>
        <picklist>
            <picklistValues>
                <fullName>Cloudinary</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Salesforce Files</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>File Upload Setting</label>
    <pluralLabel>File Upload Settings</pluralLabel>
</CustomObject>

src/classes/Test_Factory_Service.cls
@isTest
public class Test_Factory_Service
{
    static testMethod void Test_Factory_Service()
    {
        Service service = Factory_service.createDefaultService();
        Service service2 = Factory_service.createService('Cloudinary');
        //System.assertEquals(service.serviceName, service2.serviceName);
        System.assertEquals('Cloudinary', service2.serviceName);
    }
    
    static testMethod void Test_Find_By_External_Id()
    {
        Service service = Factory_service.createDefaultService();
        
        External_File__c file = service.findFileByExternalId('abc');
        
        System.assertEquals(file, null);
    }
    
    static testMethod void Test_Relate_File() {
        External_File__c f = new External_File__c();
        insert f;
        Case c = new Case();
        insert c;
        
        Service service = Factory_service.createDefaultService();
        
        List<External_File_Relationship__c> rels = service.relateFile(f, new List<String>{ c.Id });
        
        System.assertEquals(rels[0].Object_Id__c, c.Id);
        
    }
    
    static testMethod void Test_Relate_File_Tags() {
        External_File__c f = new External_File__c();
        insert f;
        
        Case c = new Case();
        insert c;
        
        Service service = Factory_service.createDefaultService();
        
        List<External_File_Relationship__c> rels = service.relateFile(f, new List<String>{ c.Id }, new List<String>{ 'Create', 'Update' });
        
        System.assertEquals(rels[0].Object_Id__c, c.Id);
        System.assert(rels[0].Tags__c.contains('Create'));
        System.assert(rels[0].Tags__c.contains('Update'));
    }
    
    static testMethod void Test_Factory_Service_NoneFound()
    {
        Exception except;
        try{
            Service service = Factory_service.createService('SERICETHATDOESNtEXIST');
        }catch(Exception e){
            except = e;
        }
        System.assert(except != null);
        System.assertEquals(except.getMessage(), 'Service SERICETHATDOESNtEXIST cannot be found');
    }
    
    static testMethod void Test_Factory_Service_SalesforceFiles()
    {
        Exception except;
        try{
            Service service = Factory_service.createService('Salesforce Files');
            System.assertEquals('Salesforce', service.serviceName);
        }catch(Exception e){
            except = e;
        }
        
    }

    static testMethod void testgetDefaultServiceName(){
        File_Upload_Setting__mdt defaultSettings = [select id,API_Key__c,Private_Key__c,Config_JSON__c,Service__c from File_Upload_Setting__mdt where Is_Default__c = true limit 1];
        
       String defaultsetting=Factory_Service.getDefaultServiceName();
       System.assertEquals(defaultSettings.Service__c,defaultsetting);
    }
}