src/objects/File_Upload_Setting__mdt.object
<CustomObject>
    <fields>
        <fullName>API_Key__c</fullName>
        <label>API Key</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Config_JSON__c</fullName>
        <label>Config JSON</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Private_Key__c</fullName>
        <label>Private Key</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Service__c</fullName>
        <label>Service</label>
        <picklist>
            <picklistValues>
                <fullName>Cloudinary</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Salesforce Files</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>File Upload Setting</label>
    <pluralLabel>File Upload Settings</pluralLabel>
</CustomObject>

src/classes/Test_Signature_Cloudinary.cls
@isTest
public class Test_Signature_Cloudinary
{
    static testMethod void Test_Signature_Cloudinary()
    {
        Signature_Cloudinary sign = new Signature_Cloudinary([select id,API_Key__c,Private_Key__c,Config_JSON__c from File_Upload_Setting__mdt where Service__c = 'Cloudinary' limit 1]);
        Map<String,Object> parametersToSign = new Map<String,Object>();
        parametersToSign.put('test','test');
        System.assertEquals(sign.getSignature(parametersToSign), sign.getSignature('test=test'));
        System.assert(String.isNotBlank(sign.getSignature(parametersToSign)));
    }
}